import sys
import random
import re
from string import ascii_uppercase

if len(sys.argv) < 3:
    print("Usage: python gen.py FILE... OUTPUT")
    exit(0)

content = id = ""
for i in range(12):
    id += random.choice(ascii_uppercase)


for p in sys.argv[1:-1]:
    path = re.sub("[^0-9a-zA-Z]+", "_", p)

    with open(p, "rb") as f:
        data = f.read()
        f.close()

    hex_list = ""
    for i, byte in enumerate(data):
        if hex_list:
            hex_list += ", "
        if i % 12 == 0:
            hex_list += "\n  "
        hex_list += f"{byte:#0{4}x}"

    hex_list += ", 0x00"
    code = f"""\
// {p}
static unsigned char {path}[] = {{\
{hex_list}
}};
static unsigned int {path}_len = {len(data) + 1};
    \n"""

    content += code

template = f"""\
// Generated by cwctl/gen.py, change will be overridden.

#ifndef _EMBED_GENERATED_{id}
#define _EMBED_GENERATED_{id}

{content}

#endif
"""

with open(sys.argv[-1], 'w') as f:
    f.write(template);
    f.close()
